# Generated by Django 4.0.4 on 2022-06-17 07:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=50, unique=True, verbose_name='이메일')),
                ('password', models.CharField(max_length=50, verbose_name='비밀번호')),
                ('fullname', models.CharField(max_length=50, verbose_name='이름')),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=256, verbose_name='한 줄 소개')),
                ('age', models.IntegerField(verbose_name='나이')),
                ('category', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user.category', verbose_name='카테고리')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user.user', verbose_name='사용자')),
            ],
        ),
    ]
